export default function Head() {
  return (
    <>
      <title>Self Taught: Self-hosted project manager for the self-taught engineer</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta property="og:title" content="ChatGPT: Optimizing Language Models for Dialogue" />
      <link rel="icon" type="image/svg+xml" href="/static/logo.svg" />
    </>
  )
}
